from tortoise import fields
from tortoise.models import Model


class StudentAcademicRecord(Model):
    """学籍成绩合并表：Excel 每人一行，对应数据库一行。"""

    id = fields.IntField(pk=True)

    grade = fields.IntField(null=True, description="年级")
    student_id = fields.CharField(max_length=32, index=True, description="学号")
    name = fields.CharField(max_length=64, null=True, description="姓名")
    name_pinyin = fields.CharField(max_length=128, null=True, description="姓名拼音")
    gender = fields.CharField(max_length=16, null=True, description="性别")
    teaching_department = fields.CharField(max_length=128, null=True, description="上课院系")
    major_name = fields.CharField(max_length=128, null=True, description="专业名称")
    major_direction_name = fields.CharField(max_length=128, null=True, description="专业方向名称")
    class_name = fields.CharField(max_length=128, null=True, description="班级")
    campus = fields.CharField(max_length=64, null=True, description="校区")
    admission_subject = fields.CharField(max_length=64, null=True, description="招生学科")
    minor_major_name = fields.CharField(max_length=128, null=True, description="辅修专业名称")
    birth_date = fields.DateField(null=True, description="出生日期")
    enrollment_year = fields.IntField(null=True, description="入学年份")
    education_level = fields.CharField(max_length=64, null=True, description="培养层次")
    research_direction = fields.CharField(max_length=128, null=True, description="研究方向")
    supervisor_name = fields.CharField(max_length=64, null=True, description="导师姓名")
    ethnicity = fields.CharField(max_length=64, null=True, description="民族")
    native_place = fields.CharField(max_length=128, null=True, description="籍贯")
    political_status = fields.CharField(max_length=128, null=True, description="政治面貌")
    hongkong_macao_taiwan_overseas = fields.CharField(max_length=64, null=True, description="港澳台侨外")
    health_status = fields.CharField(max_length=64, null=True, description="健康状况")
    phone = fields.CharField(max_length=32, null=True, description="电话")
    pe_standard = fields.CharField(max_length=64, null=True, description="体育达标")
    course_selection_group = fields.CharField(max_length=128, null=True, description="选课组")

    major_course_count = fields.IntField(null=True, description="专业课_课程数")
    major_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="专业课_平均分")
    major_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="专业课_最高分")
    major_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="专业课_最低分")
    major_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="专业课_方差")

    subject_basic_course_count = fields.IntField(null=True, description="学科基础课_课程数")
    subject_basic_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="学科基础课_平均分")
    subject_basic_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="学科基础课_最高分")
    subject_basic_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="学科基础课_最低分")
    subject_basic_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="学科基础课_方差")

    general_course_count = fields.IntField(null=True, description="通识课_课程数")
    general_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="通识课_平均分")
    general_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="通识课_最高分")
    general_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="通识课_最低分")
    general_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="通识课_方差")

    required_course_count = fields.IntField(null=True, description="必修_课程数")
    required_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="必修_平均分")
    required_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="必修_最高分")
    required_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="必修_最低分")
    required_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="必修_方差")

    elective_course_count = fields.IntField(null=True, description="选修_课程数")
    elective_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="选修_平均分")
    elective_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="选修_最高分")
    elective_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="选修_最低分")
    elective_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="选修_方差")

    all_course_count = fields.IntField(null=True, description="全部课程_课程数")
    all_course_avg_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="全部课程_平均分")
    all_course_max_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="全部课程_最高分")
    all_course_min_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="全部课程_最低分")
    all_course_variance = fields.DecimalField(max_digits=10, decimal_places=4, null=True, description="全部课程_方差")

    absent_exam_count = fields.IntField(null=True, description="缺考次数")
    makeup_exam_count = fields.IntField(null=True, description="补考次数")
    retake_count = fields.IntField(null=True, description="重修次数")
    required_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="必修")
    elective_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="选修")
    other_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="其它")
    retake_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="重修学分")
    earned_total_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="获得总学分")
    failed_total_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="不及格总学分")
    major_total_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="主修总学分")
    minor_total_credits = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="辅修总学分")
    total_grade_points = fields.DecimalField(max_digits=10, decimal_places=3, null=True, description="总绩点分")
    average_credit_gpa = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="平均学分绩点")

    cet4_exam_count = fields.IntField(null=True, description="考四级次数")
    cet4_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="四级")
    cet6_exam_count = fields.IntField(null=True, description="考六级次数")
    cet6_score = fields.DecimalField(max_digits=8, decimal_places=3, null=True, description="六级")
    building = fields.CharField(max_length=64, null=True, description="楼栋")
    dormitory_name = fields.CharField(max_length=128, null=True, description="宿舍名称")
    class_teacher = fields.CharField(max_length=64, null=True, description="班主任")
    counselor = fields.CharField(max_length=64, null=True, description="辅导员")
    competition_award_count = fields.IntField(null=True, description="学科竞赛获奖次数")
    competition_award_detail = fields.TextField(null=True, description="学科竞赛获奖明细")

    source_file = fields.CharField(max_length=255, null=True, description="来源文件")
    source_sheet = fields.CharField(max_length=128, null=True, description="来源工作表")
    row_number = fields.IntField(null=True, description="Excel 行号")
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        table = "student_academic_records"
        unique_together = (("grade", "student_id"),)
