export const ROUTES = {
  portal: '/portal',
  college: {
    root: '/college',
    keyTasks: '/college/key-tasks',
    highPotential: (moduleId: string) => `/college/high-potential/${moduleId}`,
    warning: (type: string) => `/college/warning/${type}`,
    teachingCourses: '/college/teaching/courses',
    researchPlatforms: '/college/research/platforms',
    studentEmployment: '/college/student/employment',
  },
  university: {
    root: '/university',
    research: '/university/research',
    tasks: '/university/tasks',
    keyTasks: '/university/tasks',
    disciplines: '/university/disciplines',
    employment: '/university/employment',
    events: '/university/events',
    academicRisk: '/university/academic-risk',
    metrics: '/university/metrics',
    news: '/university/events',
  },
  student: {
    root: '/student',
    gpaDetail: '/student/gpa-detail',
    gpaSemester: '/student/gpa-semester',
    creditProgress: '/student/credit-progress',
    failDetail: '/student/fail-detail',
  },
} as const
