export const ROUTES = {
  portal: '/portal',
  college: {
    root: '/college',
    keyTasks: '/college/key-tasks',
    highPotential: (moduleId: string) => `/college/high-potential/${moduleId}`,
    warning: (type: string) => `/college/warning/${type}`,
    teachingCourses: '/college/teaching/courses',
    researchPlatforms: '/college/research/platforms',
    studentEmployment: '/college/student/employment',
  },
  university: {
    root: '/university',
    posture: '/university/posture',
    goals: '/university/goals',
    benchmark: '/university/benchmark',
    disciplineTalent: '/university/discipline-talent',
    research: '/university/research',
    employmentRisk: '/university/employment-risk',
    metrics: '/university/metrics',
    // legacy redirects
    tasks: '/university/goals',
    keyTasks: '/university/goals',
    disciplines: '/university/discipline-talent',
    teaching: '/university/discipline-talent',
    faculty: '/university/discipline-talent',
    employment: '/university/employment-risk',
    events: '/university/employment-risk',
    academicRisk: '/university/employment-risk',
    news: '/university/employment-risk',
  },
  student: '/student',
} as const
